# Generated by Django 4.2.4 on 2023-09-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainmenuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenuitem',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
