# Generated by Django 4.2.4 on 2023-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mainmenuitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenuitem',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
