# Generated by Django 4.2.4 on 2023-09-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mainmenuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenuitem',
            name='is_manager_only',
            field=models.BooleanField(default=False),
        ),
    ]
