# Generated by Django 4.2.4 on 2023-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ('position',)},
        ),
    ]
