# Generated by Django 4.2.4 on 2023-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_contactinfoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('position', models.PositiveSmallIntegerField()),
                ('short_desc', models.TextField(blank=True, max_length=500)),
                ('desc', models.TextField(blank=True, max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(blank=True, upload_to='events/')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ('position',),
                'unique_together': {('id', 'slug')},
            },
        ),
    ]
