# Generated by Django 4.2.4 on 2023-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
