# Generated by Django 4.2.4 on 2023-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_chef_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ('order',)},
        ),
        migrations.CreateModel(
            name='WhyChooseYummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_boxes', models.ManyToManyField(to='cafe.iconbox')),
            ],
        ),
    ]
