# Generated by Django 4.2.4 on 2023-09-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_iconbox_alter_chef_options_whychooseyummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseyummy',
            name='icon_boxes',
        ),
    ]
