# Generated by Django 4.2.4 on 2023-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_delete_whychooseyummy_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconbox',
            name='is_visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
